CREATE DATABASE employee ;
USE EMPLOYEE;


SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT 
FROM emp_record_table;

SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT,EMP_RATING 
FROM emp_record_table 
WHERE EMP_RATING <2 ;


SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT,EMP_RATING 
FROM emp_record_table 
WHERE EMP_RATING > 4 ;

SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT,EMP_RATING 
FROM emp_record_table 
WHERE EMP_RATING BETWEEN 2 AND 4 ;

SELECT concat(FIRST_NAME,' ',LAST_NAME) AS NAME 
FROM emp_record_table;



SELECT * 
from emp_record_table WHERE (DEPT = 'healthcare') 
UNION 
SELECT * 
from emp_record_table 
WHERE (DEPT = 'finance');

SELECT EMP_ID, FIRST_NAME, LAST_NAME, ROLE, DEPT, EMP_RATING, 
MAX(EMP_RATING) OVER (PARTITION BY DEPT) AS MAX_RATING 
FROM emp_record_table;


SELECT role, MIN(salary) AS min_salary, MAX(salary) AS max_salary 
FROM emp_record_table GROUP BY role;


SELECT *, 
DENSE_RANK() OVER (ORDER BY EXP DESC) AS rank_Exp 
FROM emp_record_table;

DROP VIEW empl_salary;
CREATE VIEW empl_salary AS SELECT EMP_ID, FIRST_NAME, LAST_NAME, SALARY, COUNTRY 
FROM emp_record_table 
WHERE SALARY > 6000;


SELECT	EMP_ID, FIRST_NAME, LAST_NAME, EXP 
FROM emp_record_table 
WHERE (SELECT EXP > 10) ;

DROP PROCEDURE emp_exp_Three;
DELIMITER && 
CREATE PROCEDURE emp_exp_Three () 
BEGIN
SELECT * FROM emp_record_table WHERE EXP > 3 ; 
END && 
CALL emp_exp_Three ();

DROP FUNCTION emrol ; 
DELIMITER // 
CREATE FUNCTION emrol(EXP INT) 
RETURNS VARCHAR(40) 
DETERMINISTIC
BEGIN 
DECLARE emp_role VARCHAR(40) ;
IF EXP  BETWEEN 12 AND 16 THEN 
SET emp_role = 'MANAGER' ;
ELSEIF EXP  BETWEEN 10 AND 12 THEN 
SET emp_role = 'LEAD_DATA_SCIENTIST';
ELSEIF EXP  BETWEEN 5 AND 10 THEN 
SET emp_role ='SENIOR_DATA_SCIENTIST';
ELSEIF EXP  BETWEEN 2 AND 5 THEN  
SET emp_role ='ASSOCIATE_DATA_SCIENTIST' ;
ELSEIF EXP<= 2 THEN 
SET emp_role ='JUNOR_DATA_SCIENTIST';
END IF ;
RETURN (emp_role); 
END // 

SELECT EXP, emrol(EXP)
FROM data_science_team;

DROP INDEX indx ON emp_record_table;
CREATE INDEX indx ON emp_record_table (FIRST_NAME(40));
EXPLAIN SELECT EMP_ID, FIRST_NAME, LAST_NAME FROM emp_record_table WHERE 
FIRST_NAME = 'ERIC';

SELECT EMP_ID, FIRST_NAME, LAST_NAME, SALARY, EMP_RATING , 
(SALARY + SALARY*0.05* EMP_RATING) AS BONUS_SAL 
FROM emp_record_table; 

SELECT EMP_ID,FIRST_NAME,LAST_NAME,COUNTRY,CONTINENT,
AVG(SALARY) OVER (PARTITION BY COUNTRY) AS avg_sal_cntry , 
AVG(SALARY) OVER (PARTITION BY CONTINENT) AS avg_sal_cont, 
COUNT(*) OVER (PARTITION BY COUNTRY) AS count_in_country , 
COUNT(*) OVER (PARTITION BY CONTINENT) AS count_in_continent 
FROM emp_record_table;  

